# Generated by Django 3.2.6 on 2021-08-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Manage Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, default='project_default.png', null=True, upload_to='projects/'),
        ),
    ]
