# Generated by Django 3.2.6 on 2021-09-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210831_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, default='clients/project_default.png', null=True, upload_to='projects/'),
        ),
    ]
