# Generated by Django 3.2.6 on 2021-09-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
