# Generated by Django 3.2.6 on 2021-09-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.FileField(blank=True, default='projects/project_default.png', null=True, upload_to='projects/'),
        ),
    ]
