# Generated by Django 3.2.6 on 2021-08-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('client_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientproject')),
            ],
            options={
                'db_table': 'client_project_documents',
            },
        ),
    ]
