# Generated by Django 3.2.6 on 2021-08-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_supportactivity_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='ticket_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
