# Generated by Django 3.2.6 on 2021-08-23 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_supportrequest_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportactivity',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
