# Generated by Django 3.2.6 on 2021-08-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_supportactivity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportactivity',
            name='files',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
