# Generated by Django 3.2.6 on 2021-08-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_supportactivity_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportactivity',
            name='files',
        ),
    ]
