# Generated by Django 3.2.6 on 2021-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
