# Generated by Django 3.2.6 on 2021-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'OPEN'), ('2', 'Awaiting Business Inputs'), ('3', 'With Client Review'), ('4', 'Closes'), ('5', 'Deferred')], default='0', max_length=255),
        ),
    ]
