# Generated by Django 3.2.6 on 2021-08-26 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_supportrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Open'), ('2', 'Awaiting Business Inputs'), ('3', 'With Client Review'), ('4', 'Closed'), ('5', 'Deferred')], default='0', max_length=255),
        ),
        migrations.CreateModel(
            name='SupportRequestActivityFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='TicketFiles/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.supportactivity')),
            ],
            options={
                'db_table': 'support_request_activity_files',
            },
        ),
    ]
