# Generated by Django 3.2.6 on 2021-08-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20210826_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportactivity',
            name='files',
        ),
    ]
