# Generated by Django 3.2.6 on 2021-08-28 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20210826_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
