# Generated by Django 3.2.6 on 2021-09-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20210831_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, default='clients/client_default.png', null=True, upload_to='clients/'),
        ),
    ]
