# Generated by Django 3.2.6 on 2021-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, default='clients/client_default.png', null=True, upload_to='clients/'),
        ),
    ]
