# Generated by Django 3.2.6 on 2021-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_alter_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
