# Generated by Django 3.2.6 on 2021-09-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_client_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Manage Clients'},
        ),
    ]
