# Generated by Django 3.2.6 on 2021-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_client_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Manage Clients'},
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='ticket_type',
            field=models.CharField(choices=[('1', 'Service Request Ticket'), ('2', 'Incident Ticket'), ('3', 'Problem Ticket'), ('4', 'Change Request Ticket')], default='1', max_length=255),
        ),
    ]
