# Generated by Django 3.2.6 on 2021-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_auto_20210909_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='ticket_type',
            field=models.CharField(choices=[('1', 'Service Related'), ('2', 'Sales Related'), ('3', 'Billing Related'), ('4', 'Others')], default='1', max_length=255),
        ),
    ]
