# Generated by Django 3.2.6 on 2021-09-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_alter_client_options'),
        ('clients', '0027_auto_20210909_1537'),
    ]

    operations = [
    ]
