# Generated by Django 3.2.6 on 2021-09-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_alter_supportrequest_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='amc_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='project_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
