# Generated by Django 3.2.6 on 2021-09-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_merge_20210909_1211'),
        ('clients', '0029_auto_20210912_1137'),
    ]

    operations = [
    ]
