# Generated by Django 3.2.6 on 2021-09-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_merge_20210912_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientproject',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Client Projects'},
        ),
        migrations.AlterModelOptions(
            name='supportrequest',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Support Requests'},
        ),
    ]
