# Generated by Django 3.2.6 on 2021-09-14 09:29

from django.db import migrations, models
import my_lib.views


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_alter_clientproject_next_amc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='next_amc_date',
            field=models.DateField(default=my_lib.views.date_next_year),
        ),
    ]
