# Generated by Django 3.2.6 on 2021-09-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amcrenewal',
            name='reference',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
