# Generated by Django 3.2.6 on 2021-09-08 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_amcrenewal_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amcrenewal',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='amcrenewal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
