# Generated by Django 3.2.6 on 2021-09-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_amcrenewal_renewed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amcrenewal',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Manage AMC Renewals'},
        ),
    ]
