# Generated by Django 3.2.6 on 2021-09-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_alter_amcrenewal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amcrenewal',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
